Hello Microverse
feyisakedir/Hello-World pull request #2
Opened 2023-04-25 20:33 UTC by feyisakedir

Pull Request

2023-04-25 21:18 UTC, V-Blaze requested changes
## Hi @, 

# Almost there 🟡 

## NB: I noticed that you closed the first pull request and submitted a new one. According to Microverse requirements, you are not supposed to merge or close a pull request until it has been reviewed and approved by a code reviewer, Please in your subsequent projects, do not merge or close an unapproved pull request. Happy Coding! :+1: 

![giphy](https://user-images.githubusercontent.com/107632780/228988839-8679641a-a056-4909-a594-bcecacef173b.gif)


Great work so far, You have come a long way, keep moving forward👏 👍  
You've done well implementing the project requirements, and some changes from the previous reviewers, but there are still some issues I think you need to improve on. 😄 👋 


 ## Highlights
- Linters are setup correctly✔
- Used Microverse readme template. :green_apple: 

 ## Required Changes ♻️

- [ ] According to the project requirement
> Remember to document your work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).

You are supposed to make your project look professional including your pull request, I'll suggest you edit your pull request and make a good summary, You can include the task or the changes you made in this branch as the summary. :smile: 

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-25 21:18 UTC, V-Blaze commented on README.md
>  > Describe the tech stack and include only the relevant sections that apply to your project.
- [ ] Great job using the recommended Microverse readme template. :zap: :+1: , But as stated in the project requirement, you need to customize the readme file for your specific project, like the `Key Feature, Future Features`etc.
> Add descriptive README file to your project - please use [this template](https://github.com/microverseinc/readme-template) but remember to customize it to your project.

- Please go through the readme file and personalize the content, I'll also give some suggestions. Remember to remove the placeholder comments. :+1: :smile:

2023-04-25 21:18 UTC, V-Blaze commented on README.md
> +- [ ] **[.js]**
- [ ] In this section, I'll suggest you remove the comment `Describe 1 - 3 features you will add to the project.` and then add three features that you will be adding to your project later. :smile: :+1:

2023-04-25 21:18 UTC, V-Blaze commented on .github/test.md
- [ ] According to the project requirement you are supposed to create a `test.md` file at the root directly of your project and then add it to the `.gitignore` file. Please move this file to your project root or delete this and rename the one in the project root correctly. :+1: :smile:

2023-04-25 21:18 UTC, V-Blaze commented on .github/.gitignore
- [ ] The `.gitignore` file is meant to be in the root of your project, Please I'll suggest you move this file to your project root. :sun_with_face:

2023-04-26 07:44 UTC, merged

2023-04-26 11:46 UTC, feyisakedir commented on README.md
> +- [ ] **[.js]**
Can I create new pull Request?

2023-04-26 14:04 UTC, Eternalgratis reviewed
# Status: Required Changes ♻️
Hi @feyisakedir , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but some are still not addressed yet.

![almost-there](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

 ## Highlights
✅ You used the correct GitHub flow
✅ Descriptive pull request message
✅ linter error checks validated


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-26 14:04 UTC, Eternalgratis commented on README.md
>    - [Setup](#setup)
- Please consider adding the setup of your project here as well

2023-04-26 14:14 UTC, Eternalgratis reviewed
# Status: Required Changes ♻️
Hi @feyisakedir , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but some are still not addressed yet.

![almost-there](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

 ## Highlights
✅ You used the correct GitHub flow
✅ Descriptive pull request message
✅ linter error checks validated


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-26 14:14 UTC, Eternalgratis commented on README.md
>      - [Key Features](#key-features)
Great job on implementing some of the changes requested by the previous reviewer. However, there are a few to make some adjustments to

- Kindly add the key features in line 17 [Key Features](#key-features) of this particular project. The essence of a customized Readme is to help anyone visiting your repo to have an idea of what the project is about

2023-04-26 17:42 UTC, frank1738 reviewed
Hi @feyisakedir , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] You have submitted a pull request that has already been merged

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-04-26 17:47 UTC, feyisakedir commented
It's not invalid you're the first person said invalid code
I can't create new PR b/c the previous reviewer comment is necessary

On Wed, Apr 26, 2023, 8:42 PM Frankline Osoro ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
>
> Hi @feyisakedir <https://github.com/feyisakedir> ,
>
> While you made a great effort in this project, unfortunately, I cannot
> proceed to review your code.
> Invalid Code Review Request
>
>    - You have submitted a pull request that has already been merged
>
> Your Code Review Request will be marked as invalid in your Dashboard, so
> please submit a new one once you are ready 🙏
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/feyisakedir/Hello-World/pull/2#pullrequestreview-1402507492>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYHUAFTG3ZG5MUZLS2QIWXLXDFNCHANCNFSM6AAAAAAXLQHLAU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>